#!/bin/sh
# AppRun do AppImage do reforja: localiza a raiz e executa o binario congelado.
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
exec "${HERE}/usr/bin/reforja" "$@"
